# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zises Strategic Communications
email: bryan@zis.es
description: > # this means to ignore newlines until "baseurl:"
  Chicago public relations, communications and political consulting.
baseurl: # "/zises-communications/" the subpath of your site, e.g. /blog
url: "http://zis.es" # the base hostname & protocol for your site
twitter_username: bryan_z
github_username: bryan_z

# Build settings
markdown: kramdown
